#!/usr/bin/perl -w
use strict;
use IO::Socket::INET;
use IO::Select;

## Set up the simulators and jack pipes between them.

## Ensure Jack is running
if(`jack_wait -c 2>/dev/null` !~ /^running$/m){
    die "Jack Audio Server is not running";
};

## Ensure mod-host is running.
my $MH_PID = qx(pgrep -x mod-host);
chomp $MH_PID;
$MH_PID or die "cfgEffects: mod-host not running";

## Pass the configuration file for `jack_midi` so only pedals required
## are created
my $jack_midi_cfg = shift or die "Pass the configuration file for `jack_midi`";
-r $jack_midi_cfg or die "$!: Cannot read $jack_midi_cfg";

# Get the names of the pedals that need to be created
my @cfg_names = map{
    chomp;
    s/^j \d+ //;
    $_
} grep {/^j \d+ /} `cat $jack_midi_cfg`;

## Get the set of commands to initialise the LV2 effect simulators and
## the commands to activate them.
my ($lv2_init_ref, $lv2_activation_ref) = &getLV2(@cfg_names);
my @lv2_init = @$lv2_init_ref;
my %lv2_activation = %$lv2_activation_ref;

## TODO: Alternative (non-LV2) effects

## The directory to write pedal definitions to.  Ensure it exists
my $pedal_dir = $ENV{PEDAL_DIR};
if(!defined($pedal_dir)){
    $pedal_dir = $0;
    $pedal_dir =~ s/\/[^\/]*$/\/PEDALS/;
}
-e $pedal_dir or mkdir $pedal_dir;
-d $pedal_dir or die "'$pedal_dir' not a directory";

## Clear out old files.  There are is a README.md documentation file
## that should not be deleted.
opendir(my $dir, $pedal_dir) or die "$!: $pedal_dir";
foreach my $fn (readdir($dir)){
    $fn =~ /^\./ and next;
    $fn eq 'README.md' and next;
    my $path_to_delete = $pedal_dir .'/'. $fn;
    unlink($path_to_delete) or die "$!: $path_to_delete";
}

# The new files that define effects: Initialisation
my $initialise_fn = $pedal_dir.'/Initialise';
{
    open(my $fh, ">", $initialise_fn) or die "$!: $initialise_fn";
    print $fh join("\n", @lv2_init)."\n";
    close($fh) or die  "$!: $initialise_fn";
}

# The new files that define effects: Activation
foreach my $pedal_name (sort keys %lv2_activation){
    my $activation_fn = $pedal_dir."/$pedal_name";
    open(my $fh, ">", $activation_fn) or die "$!: $activation_fn";
    my @activaton_cmd = @{$lv2_activation{$pedal_name}};
    print $fh join("\n", @activaton_cmd)."\n";
    close($fh) or die "$!: $activation_fn";
}

## Initialise the effects

## Set up the effects, and the parameters
my @mh_commands = map{chomp; s/^mh //; $_} grep {/^mh /} `cat $initialise_fn`;
&mod_host(\@mh_commands);
my @jack_initial = map{chomp; s/^jack //; $_} grep {/^jack /} `cat $initialise_fn`;
foreach my $jcmd ( @jack_initial ) {
    &handle_jack( "connect $jcmd" );
}

# The last connection is from the mixer to the output.
&handle_jack("connect qzn3t_mixer:output_1 system:playback_1");

# Finished now
warn "DBG cfgEffects: End\n";
exit 0;

## `handle_mh_cmd` and `mod_host` set up the LV2 simulators.
## `mod_host` is passed an array of commands to send to `mod-host`
sub handle_mh_cmd( $$ ) {
    my ($sock, $cmd) = @_;
    print $sock "$cmd\n";

    my $result = '';
    my $timeout = 0.1;

    my $sel = IO::Select->new();
    $sel->add($sock);
    if ($sel->can_read($timeout)) {
	# Read up to 4096 bytes at once
	my $bytes_read = sysread($sock, $result, 4096);
	if (!defined $bytes_read) {
	    die "Read error: $!";
	}
	# Handle potential remaining data
	while ($sel->can_read(0)) {  # Non-blocking check
	    my $more_data;
	    $bytes_read = sysread($sock, $more_data, 4096);
	    $result .= $more_data;
	}
    }

    # warn "handle_mh_cmd: \$result $result\n";
    if($result =~ /resp ([\-0-9]+)/){
	# If status is a negative number an error has
	# occurred. The table below shows the number of each
	# error.

	# status	error
	# -1	ERR_INSTANCE_INVALID
	# -2	ERR_INSTANCE_ALREADY_EXISTS
	# -3	ERR_INSTANCE_NON_EXISTS
	# -4	ERR_INSTANCE_UNLICENSED
	# -101	ERR_LV2_INVALID_URI
	# -102	ERR_LV2_INSTANTIATION
	# -103	ERR_LV2_INVALID_PARAM_SYMBOL
	# -104	ERR_LV2_INVALID_PRESET_URI
	# -105	ERR_LV2_CANT_LOAD_STATE
	# -201	ERR_JACK_CLIENT_CREATION
	# -202	ERR_JACK_CLIENT_ACTIVATION
	# -203	ERR_JACK_CLIENT_DEACTIVATION
	# -204	ERR_JACK_PORT_REGISTER
	# -205	ERR_JACK_PORT_CONNECTION
	# -206	ERR_JACK_PORT_DISCONNECTION
	# -301	ERR_ASSIGNMENT_ALREADY_EXISTS
	# -302	ERR_ASSIGNMENT_INVALID_OP
	# -303	ERR_ASSIGNMENT_LIST_FULL
	# -304	ERR_ASSIGNMENT_FAILED
	# -401	ERR_CONTROL_CHAIN_UNAVAILABLE
	# -402	ERR_LINK_UNAVAILABLE
	# -901	ERR_MEMORY_ALLOCATION
	# -902	ERR_INVALID_OPERATION

	#     A status zero or positive means that the command was
	#     executed successfully. In case of the add command,
	#     the status returned is the instance number. The
	#     value field currently only exists for the param_get
	#     command.
	if($1 < 0 and $1 != -2){
	    print  STDERR "Error setLv2: Fail command: $cmd >>  $result\n";
	}else{
	    return 1;
	}
    }else{
	print STDERR "Error setLv2: Unexpected result: '$result' \n";
    }
    return 0;
}

sub mod_host( $ ){
    my $cmds = shift or die;
    my @cmds = @$cmds;

    my $remote = "localhost";
    my $port = $ENV{MOD_HOST_PORT};
    defined $port or $port = 5555;
    my $mod_host_port_p = $port;
    my $sock = new IO::Socket::INET( PeerAddr => 'localhost',
				     PeerPort => $mod_host_port_p,
				     Proto => 'tcp') or
	die "cfgEffects: $!: Failed to connect to mod-host localhost:$mod_host_port_p ";

    ## Debugging why some effects randomly fail to be added
    my $failed = 0;

    foreach my $cmd (@cmds){
	# warn "Process: \$cmd($cmd) \n";
	if(!$failed){
	    &handle_mh_cmd($sock, $cmd);
	}else{
	    die "cfgEffects: Process: \$cmd($cmd) \n";
	}
	## If command was an `add` check the effects got added
	if($cmd =~ /^add.+\s(\d+)/){
	    my $max_retries = 5;
	    my $retry_delay = 0.1;  # seconds
	    my $i = 0;
	    for (; $i < $max_retries; $i++) {
		last if grep { /effect_$1/ } `jack_lsp`;
		select(undef, undef, undef, $retry_delay);  # Non-busy sleep
	    }
	    die "effect_$1 failed to appear in JACK for command: $cmd" if $i == $max_retries;
	}
    }
}

## Handle a connecet or disconnect jack command: When there are no
## spaces in MIDI device names
sub handle_jack( $ ){
	 my $str = shift or die;
	 my ($cmd, $lhs, $rhs) = split(/\s/, $str);;
	 return &handle_jack_3($cmd, $lhs, $rhs);
}

## Handle a connecet or disconnect jack command: When there spaces in
## MIDI device names
sub handle_jack_3( $$$ ){
    ## Passed a Jack command execute it.  There are two: "connect"
    ## and "disconnect"
    my ($cmd, $lhs, $rhs) = @_;

    # warn "$cmd ";
    if($cmd eq 'connect'){ ## (\S+)\s+(\S+)\s*$/){
	## Commanded to make a connection.  Check first if it exists
	## and there is nothing to do
	if( ! &test_jack_connection($lhs, $rhs)){
	    `jack_connect '$lhs' '$rhs'`;
	}
    }elsif($cmd =~ /^disconnect (\S+)\s+(\S+)\s*$/){
	if(  &test_jack_connection($1, $2)){
	    `jack_disconnect '$lhs' '$rhs'`;
	}
    }
}
## Check for a connetion between two ports.
sub test_jack_connection( $$ ) {
    my ($lhs, $rhs) = @_;
    my @jack_lsp = `jack_lsp -c`;


    my $c_lhs;
    my $c_rhs;

    my $result = 0;
    my $state = "";
    foreach my $line (@jack_lsp){
	chomp $line;
	if($line =~ /^$lhs$/){
	    $state = $lhs;
	    next;
	}elsif($line =~ /^\S/){
	    $state = "";
	    next;
	}elsif($line =~ /^\s+$rhs$/){
	    if($state){
		return 1;
		exit;
	    }
	}
    }
    return 0;
}

## From select(2) section of perlfunc
sub fhbits {
    my @fhlist = @_;
    my $bits = "";
    for my $fh (@fhlist) {
	vec($bits, fileno($fh), 1) = 1;
    }
    return $bits;
}

## Passed a file name and a start index, returns a HASH ref that
## describes all the actions required to instantiate a pedal board.
## The `index` is used to identify each effect.  This function is
## called for all the pedal boards at the same time, and each one must
## be independent.  So by initialising the index in the arguments,
## each effect, in a pedal board, across all pedal boards, can have a
## unique index
sub process_lv2_turtle( $$ ) {
    my $fn = shift or die;
    my $index = shift or die; ## Zero is invalid index
    $fn =~ /([^\/]+).ttl$/ or die $fn;
    my $pedal_board_name = $1;

    ## Break up an effect name and port.  This we do a lot
    my $name_port = sub {
	my $name_port = shift or die;
	if($name_port =~ /^(\S+)\/(\S+)/){
	    return [$1, $2];
	}else{
	    print STDERR "Error cfgEffects: $pedal_board_name bad: $name_port\n";
	    return undef;
	}
    };

    ## Strip angle brackets from around a value.  We do this a lot as
    ## it turns out
    my $strip_ang = sub {
	my $v = shift or die;
	$v =~ s/^<//;
	$v =~ s/>$//;
	$v
    };

    unless( -r $fn ){
	return ();
    }

    ## Decode the Turtle file
    my @lines = read_turtle($fn) or die "Cannot process $fn";

    ## We need to get the instructions needed to initialise this
    ## effect and turn it on.

    ## Need:

    ## add <lv2_uri> <instance_number> Record what instance number
    ## goes with what effect so it can be communicated to the user.

    ## param_set <instance_number> <param_symbol> <param_value>
    ## Set up the effect in the way it was saved from mod-ui

    ## Triples and their meanings
    ## predicate == "lv2:prototype" => subject is an effect, objecty is the URL.
    ## ......... <DS1> lv2:prototype <http://moddevices.com/plugins/mod-devel/DS1>
    ## _________ Use for the "add" command
    ## predicate == ingen:arc => object names a Jack connection.
    ## .........   "<> ingen:arc _:b1"
    ## _________  Use in "jack_connect" commands
    ## predicate == lv2:port => subject is a device and object is a port of that device
    ## ......... <DS1> lv2:port  <DS1/Out1>
    ## ......... <DS1> lv2:port  <DS1/Tone>

    ## predicate == ingen:tail => subject is a Jack connection, object is where it starts
    ## predicate == ingen:head => subject is a Jack connection, object is where it ends
    ## .........  "_b2 ingen:tail <bitta/output>"
    ## .........  "_b1 ingen:head <playback_1>
    ## predicate == a  => subject is of type object
    ## .........  <DS1/In> a lv2:AudioPort
    ## .........  <DS1/In> a lv2:InputPort
    ## _________  Use in "jack_connect" commands
    ## .........  <bitta/drywet> a lv2:ControlPort
    ## _________  Use in "param" commands
    ## predicate == "ingen:value" and subject == a control port of a device => object is a value to set a port
    ## .........  <bitta/drywet> ingen:value 1.000000
    ## _________  Use for the "param" command

    ## .........
    ## .........

    ## Each effect is setup in this hash.
    ## Indexed by the name
    my %effects = ();

    ## The internal pipes between the effects that make up the pedal
    ## board and the output.  These are established at startup for all
    ## effects
    my @persistant_jack_pipes = ();

    ## The input audio pipes, and output.  Connecting these enables the effect
    ## chain that makes up the pedal board.  (TODO: What about MIDI
    ## LV2 effects?)
    my @activation_jack_pipes = ();

    ## each entry om @line is a triple as text.  Convert into an
    ## array of arrays, each with three elements: subject, predicate,
    ## object
    my @triples = map {
	chomp;
	/^(\S+)\s+(\S+)\s+(.+)/ or die $_;
	[$1, $2, $3]
    } @lines;

    ## Get the commands to add
    my @prototypes = grep {$_->[1] eq "lv2:prototype" } @triples;

    # To map numbers names
    my %name_number = ();
    my %number_name = ();

    foreach my $prototype (@prototypes){
	my ($name, $predicate, $uri) = @$prototype;

	## The name and uri are in angle brackets
	$name = &$strip_ang($name);
	$uri = &$strip_ang($uri);

	$predicate eq "lv2:prototype" or die "Error in prototypes: $predicate";

	## Initialise the effect hash
	$effects{$name} = {};
	$effects{$name}->{param} = [];
	$effects{$name}->{add} = "add $uri $index";
	$name_number{$name} = $index;
	$number_name{$index} = $name;

	my @param_set = map{/^<$name\/([^>]+)> ingen:value (.+)\s*$/; "param_set $index $1 $2" } map{join(' ', @$_)} grep{$_->[0] =~ /^<$name\//} grep { $_->[1] =~ /^ingen:value$/ } @triples;
	push(@{$effects{$name}->{param}}, @param_set);
	$index += 1;
    }

    ## Get all the control ports.  As a hash so it can be used to
    ## identify `ingen:value` commands directed at the control ports
    ## of effects in the pedal board
    my $filter_port = sub {
	## Filter for the ports wanted and get the name/port from
	## inside the angle brackets
	my $raw = shift or die;
	$raw =~ /^([a-z0-9_]+\/[a-z0-9_\:]+)$/i or
	    # Not a name/port
	    return undef;
	return $1;
    };

    my %control_ports = map{
	&$strip_ang($_) => 1
    } grep {
	defined
    }map{
	&$filter_port(&$strip_ang($_->[0]))
    }grep {
	$_->[1] eq 'a' && $_->[2] eq 'lv2:ControlPort'
    } @triples;

    ## Get all the values for control ports
    my %control_port_values = map {
	&$strip_ang($_->[0]) => $_->[2]
    } grep {
	defined($control_ports{&$strip_ang($_->[0])})
    }grep{
	$_->[1] eq 'ingen:value'
    }grep{
	## These are some sort of global setting
	## TODO: Document
	$_->[0] !~ /^:/
    }@triples;

    # ## Set up the `param set` commands in effects
    foreach my $port (keys %control_port_values){
	my $value = $control_port_values{$port};
	$port =~ /([a-z_0-9]+)\/([\:a-z0-9_]+)/i or
	    die "Badly formed port: $port";
	my $name = $1;
	my $port = $2;
	my $number = $name_number{$name};
	defined($number) or die "Unknown name: $name";
	my $command = "param_set $number $port $value";
	push(@{$effects{$name}->{param}}, $command);
    }

    ## Build jack connections
    my @jack_pipes = grep{
	$_->[1] =~ /^ingen:tail$/ or
	$_->[1] =~ /^ingen:head$/
    }@triples;

    # There are two sorts of pipe: Internal pipes between effects, and
    # to output, are created at startup.  Activation pipes, pipes from
    # input (capture_N) to first effect in chain
    my @jack_internal_pipes = ();
    my @jack_activation_pipes = ();

    foreach my $pipe (@jack_pipes){
	# `$pipe` is the name of the pipe.  The subject of the triple

	# Get the subject, predicate, and object for both ends of the pipe
	my @records = map {
	    [$_->[0], $_->[1], &$strip_ang($_->[2])]
	} grep {
	    # Filter by name
	    $_->[0] eq $pipe->[0]
		# ## Do not implement MIDI yet.  MIDI pipes eq
		# ## 'midi_merger_out' for now, the only one I have
		# ## seen.  TODO: Make some more pedal boards with MIDI
		# ## controls and watch this die here
		# and $->[2] ne 'midi_merger_out'
	}@triples;

	## Filter out some mysterious MIDI records
	join("", map{$_->[2]} @records) =~ /midi_merger_out/ and next;
	join("", map{$_->[2]} @records) =~ /midi_capture_2/ and next;

	# One "ingen:tail" and one "ingen:head"
	scalar(@records) == 2 or die "Pipe is bad";

	my @tail = grep {$_->[1] eq "ingen:tail"} @records;
	scalar @tail == 1 or  die "Pipe is bad";

	my @head = grep {$_->[1] eq "ingen:head"} @records;
	scalar @head == 1 or  die "Pipe is bad";

	# Activation connections are connected to system:capture_N
	if($tail[0]->[2] =~ /^capture_\d+$/ and
	       $head[0]->[2] =~ /^playback_(\d+)$/){
	    ## A connection directly from capture to playback
	    # For now we only handle pipes to `system:playback_1`
	    if($1 != 1){
		$fn =~ /\/([^\/]+)$/;
		warn "DBG cfgEffects: Pipes to outputs other than system:playback_1 not well supported: $1 \n";
		# next;
	    }
	    my $connection = "system:$tail[0]->[2] system:$head[0]->[2]";
	    push(@jack_activation_pipes, $connection);
	    next;
	}elsif($tail[0]->[2] =~ /^capture_\d+$/ ){
	    ## A connection from the system input
	    my $name_port = &$name_port($head[0]->[2]) or die;
	    my $number = $name_number{$name_port->[0]};
	    my $p = "system:$tail[0]->[2] effect_$number:$name_port->[1]";
	    push(@jack_activation_pipes, $p);
	    next;
	}elsif($head[0]->[2] =~ /^playback_(\d)+$/){
	    # Output pipe.
	    # For now we only handle pipes to `system:playback_1`
	    if($1 != 1){
		warn "DBG cfgEffects: Pipes to outputs other than system:playback_1 not supported: $pipe\n";
		next;
	    }
	    my $name_port = &$name_port($tail[0]->[2]) or die;
	    my $number = $name_number{$name_port->[0]};
	    my $p = "effect_$number:$name_port->[1] system:$head[0]->[2]";
	    push(@jack_activation_pipes, $p);
	    next;
	}

	## This is an internal pipe
	my $lhs_name_port = &$name_port($tail[0]->[2]) or die;
	my $lhs = "effect_".$name_number{$lhs_name_port->[0]}.":".
	    $lhs_name_port->[1];
	my $rhs_name_port = &$name_port($head[0]->[2]) or die;
	my $rhs = "effect_".$name_number{$rhs_name_port->[0]}.":".
	    $rhs_name_port->[1];
	my $p = "$lhs $rhs";
	push(@jack_internal_pipes, $p);
    }

    ## Remove duplicates from the jack pipes and parameter definitions
    my %d = ();
    %d = map{$_ => 1} @jack_internal_pipes;
    @jack_internal_pipes = keys %d;
    %d = map{$_ => 1} @jack_activation_pipes;
    @jack_activation_pipes = keys %d;
    foreach my $name (keys %effects){
	%d = map{$_ => 1} @{$effects{$name}->{param}};
	@{$effects{$name}->{param}} = keys %d;
    }

    my %result = (
	"effects" => \%effects,
	"index" => $index,
	"jack_activation_pipes" => \@jack_activation_pipes,
	"jack_internal_pipes" => \@jack_internal_pipes,
	"number_name" => \%number_name,
	"pedal_board_name" => $pedal_board_name
	);
    return %result;

}

## Read a ttl, Turtle, document
## Return an array of triples (RDF)
sub read_turtle( $ ){
    my $fn = shift or die "Pass a Turtle file to process";
    open(my $fh, $fn) or die "$!: $fn";
    my @lines = map{chomp; $_} grep {$_ !~ /^\s*#/} <$fh>;

    ## Create prefixs
    my %prefix_lines = map{
	/^\@prefix (\S*):\s+<(\S*)>\s*\.$/;
	defined($1) or die "Prefix undefined: $_";
	defined($2) or die "Prefix subject undefined: $_";
	$1 => $2
    } grep{/^\@prefix /} @lines;
    @lines = grep {$_ !~ /^\@prefix /} @lines;
    my @result = ();

    ## Turtle is broken up by '.'
    my $input = join("", @lines);

    my @input = split(' \.', $input);
    ## Process the ";"
    my @semi_colon_processed = ();
    foreach my $statement  (@input) {
	if($statement =~ /\s;\s/){
	    ## There is a ' ; ' on this line
	    ## The ; symbol may be used to repeat the subject of of triples that vary only in predicate and object RDF terms.semi_colon_processed

	    $statement =~ s/^\s*(\S+)\s+(\S+)\s+([^;]*[^;\s])\s+;// or die $statement;
	    my ($subject, $predicate, $object) = ($1, $2, $3);
	    # if($object =~ /\s/){
	    #     ## Must be a quoted string
	    #     $object =~ /"(.+)"$/ or die $object;
	    # }
	    # push(@semi_colon_processed, "$subject $predicate $object");
	    ## This next line will break if and predicate or object
	    ## has an embedded ';'
	    while(1){
		my @objects = split(/\s,\s/, $object);
		for my $o (@objects){
		    push(@semi_colon_processed, "$subject $predicate $o");
		}
		$statement =~ s/^\s*(\S+)\s+([^;]*[^;\s])\s*;?// or last;
		($predicate, $object) = ($1, $2);
	    }

	}else{
	    push(@semi_colon_processed, $statement);
	}
    }

    ## Process ' , '
    my @comma_processed = ();
    foreach my $semi (@semi_colon_processed){
	if($semi =~ / , /){
	    $semi =~ s/^(\S+)\s+(\S+)\s+(\S+)\s+,//;
	    my($subject, $predicate, $object) = ($1, $2, $3);
	    push(@comma_processed, "$subject $predicate $object");
	    my @objects = split(' , ', $semi);
	    foreach $object (@objects){
		push(@comma_processed, "$subject $predicate $object");
	    }
	}else{
	    push(@comma_processed, $semi);
	}
    }
    return @comma_processed;
}

## Return the @Initialise and pedal file definitions for LV2 pedals.
## Pass the names of the pedals required.  Only process a pedal if it
## is in that list.  LV2 pedals in Qzn3t are named for the
## `modep-mod-ui` definition name
sub getLV2 {
    my @cfg_names = @_;
    my $modep_pedal_dir = $ENV{MODEP_PEDALS};
    defined $modep_pedal_dir or $modep_pedal_dir = '/var/modep/pedalboards';
    -d $modep_pedal_dir or $modep_pedal_dir = "$ENV{HOME}/.pedalboards";
    -d $modep_pedal_dir or die "Cannot find pedalboard directory";
    -r $modep_pedal_dir or die "'$modep_pedal_dir' not readable";

    ## Output pedal definitions.  The data to initialise all pedals
    ## (at initialisation time) in `%initialise` and the data for each
    ## pedal runtime activation in `%run_tme` In both HASHs the key is
    ## the name of the pedal.  The value is an ARRAYREF a line per
    ## entry
    my %initialisation = ();
    my %run_time = ();

    ## Get the pedal board definitions
    my @fn = map{chomp;$_}
    grep {$_ !~ /manifest.ttl$/}
    grep {$_ !~ /effect.ttl$/}
    `find $modep_pedal_dir -type f -name "*.ttl"`;

    ## Each effect is uniquely identified by `$index`
    my $index = 1;

    my @add = ();
    my @param = ();
    my @jack = ();
    my @initialise_cmds = ();
    my %jack_activation = ();
    foreach my $fn (@fn){

	my %ex = &process_lv2_turtle($fn, $index);
	$index = $ex{index};

	my $board_name = $ex{pedal_board_name};
	grep {$_ eq $board_name} @cfg_names or next;
	
	my $effects = $ex{effects};
	my @lv2_names = sort keys %$effects;
	my %number_name = %{$ex{number_name}};

	my  @j_internal_pipes = @{$ex{jack_internal_pipes}};
	my  @j_activation_pipes = @{$ex{jack_activation_pipes}};

	foreach my $name (@lv2_names){
	    my $h = $effects->{$name};
	    my @k = sort keys %$h;
	    my $add = $h->{add} or die "No `add` for $name";
	    push(@add, "mh $add");
	    push(@param, map{"mh $_"} @{$h->{param}});
	}

	$jack_activation{$board_name} = $ex{jack_activation_pipes};
	push(@jack, map{"jack $_"} @{$ex{jack_internal_pipes}});
    }
    push(@initialise_cmds, @add);
    push(@initialise_cmds, @param);
    push(@initialise_cmds, @jack);
    return (\@initialise_cmds, \%jack_activation);
}
