#!/bin/sh
set -e
echo "DBG examples/mod-ui examples/modui: Kill mod-host"
sudo pkill -x mod-host || true
echo "DBG examples/mod-ui examples/modui: Kill pd"
pkill -x pd ||true
# echo "DBG examples/mod-ui examples/modui: Restart mod-host"
# sudo systemctl stop modep-mod-host
# Must sleep here or it will not work
sleep 1
echo "DBG examples/mod-ui examples/modui: Restart mod-ui"
sudo systemctl restart modep-mod-ui
echo "DBG examples/mod-ui End"
