#!/bin/sh

set -e

sudo systemctl stop modep-mod-ui
sudo systemctl stop modep-mod-host

MOD_HOST_HOME="${HOME}/mod-host"
One20PedalHome="${HOME}/120Pedal"

# Start mod-host
cd "${MOD_HOST_HOME}" || { echo "Failed to cd to ${MOD_HOST_HOME}"; exit 1; }
pkill mod-host || true  # Prevent exit if process not found

make || { echo "Make failed"; exit 1; }

export LV2_PATH=/var/modep/lv2
./mod-host -p 5555 &
MOD_HOST_PID=$!

# Give mod-host a moment to start
sleep 1

echo "DBG ** Use pgrep ** "
# Check if mod-host is still running
if ! pgrep mod-host 2>/dev/null; then
    echo "mod-host failed to start $MOD_HOST_PID"
    exit 1
fi

# Start the mixer
pd -jack -jack_name qzn3t_mixer  -inchannels 4 -outchannels 1 -r 48000 -realtime  -stderr -send "pd dsp 1"  -nogui ${One20PedalHome}/4ch-1ch-mixer.pd &

cd "${One20PedalHome}" || { echo "Failed to cd to ${One20PedalHome}"; exit 1; }

./setLV2 || { echo "setLV2 failed"; exit 1; }

./examples/sinco_pedal || { echo "sinco_pedal failed"; exit 1; }
