#!/bin/sh

set -e

sudo systemctl stop modep-mod-ui
sudo systemctl stop modep-mod-host

MOD_HOST_HOME="${HOME}/mod-host"
One20PedalHome="${HOME}/120Pedal"

# Start mod-host
cd "${MOD_HOST_HOME}" || { echo "Failed to cd to ${MOD_HOST_HOME}"; exit 1; }
echo "DBG examples/qzn3t examples/qzn3t: Kill mod-host"
pkill -x mod-host || true  # Prevent exit if process not found

make || { echo "Error examples/qzn3t Make failed for mod-host"; exit 1; }

export LV2_PATH=/var/modep/lv2
./mod-host -p 5555 &
MOD_HOST_PID=$!

# Give mod-host a moment to start
sleep 1

echo "DBG examples/qzn3t: Use pgrep ** "
# Check if mod-host is still running
if ! pgrep mod-host 2>/dev/null; then
    echo "Error examples/qzn3t: mod-host failed to start $MOD_HOST_PID"
    exit 1
fi

# Start the mixer
pd -jack -jackname qzn3t_mixer  -inchannels 4 -outchannels 1 -r 48000 -realtime  -stderr -send "pd dsp 1" -nomidi  -nojackconnect  -nogui ${One20PedalHome}/qzn3t_mixer_4_1.pd &

cd "${One20PedalHome}" || { echo "Error examples/qzn3t: Failed to cd to ${One20PedalHome}"; exit 1; }

./setLV2 || { echo "Error examples/qzn3t: setLV2 failed"; exit 1; }

./examples/sinco_pedal || { echo "Error examples/qzn3t: sinco_pedal failed"; exit 1; }

echo "DBG examples/qzn3t: qzn3t started"
