#!/bin/sh
# This sets up the SINCO pedal to switch between four effects.
# The effects are jack pipe definitions for connections to
# system:playback_1 and system_capture_1

echo "DBG examples/sinco_pedal:"
set -e

# Get the script's directory, 
THISDIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
## ...and the parent
PARENTDIR=$(CDPATH='' cd -- "${THISDIR}/.." && pwd -P)

# Configuration
CFGDIR="${PARENTDIR}/midi_driver/examples"
if [ ! -d "${CFGDIR}" ]; then
    echo "Error examples/sinco_pedal: Configuration path not found: ${CFGDIR}" >&2
    exit 1
fi

# Configuration files
TRANS_CFG="${CFGDIR}/sinco.cfg" ## SINCO MIDI pedal
JACK_CFG="${CFGDIR}/pedal.cfg" ## The set of Jack pipes 
for cfg in  "${JACK_CFG}" "${TRANS_CFG}"; do
    if [ ! -f "${cfg}" ]; then
        echo "Error examples/sinco_pedal: Config file not found: ${cfg}" >&2
        exit 1
    fi
done

# Set paths to executables
MIDI_DRIVER_PATH="${PARENTDIR}/midi_driver/target/release"
if [ ! -d "${MIDI_DRIVER_PATH}" ]; then
    echo "Error examples/sinco_pedal: MIDI driver path not found: ${MIDI_DRIVER_PATH}" >&2
    exit 1
fi
READ="${MIDI_DRIVER_PATH}"/read_midi
TRANS="${MIDI_DRIVER_PATH}"/translate_midi
JACK="${MIDI_DRIVER_PATH}"/jack_midi

if pgrep -x "read_midi" >/dev/null; then
    echo -n "DBG examples/sinco_pedal: Kill read_midi"
    pkill -x "read_midi" && echo "DBG examples/sinco_pedal: Stopped read_midi" || echo "Error examples/sinco_pedal: Failed to stop read_midi"
fi

for cmd in "$READ" "$TRANS" "$JACK"; do
    if ! [ -x "${cmd}" ]; then
	echo "Error examples/sinco_pedal: Command not found: ${cmd}" >&2
	exit 1
    fi
done
# Run the pipeline
($READ SINCO | $TRANS "${TRANS_CFG}" | $JACK "${JACK_CFG}")&

echo "DBG examples/sinco_pedal: sinco_pedal pipeline started"
