[package]
name = "midi_driver"
version = "0.1.0"
edition = "2021"

# [[bin]]
# ## Read a MIDI device and output the triples
# name = "read_midi"
# path = "src/read_midi.rs"

# [[bin]]
# ## Read the tripples and translate them
# name = "translate"
# path = "translate.rs"

[dependencies]
alsa = "0.7.0"
jack = "0.11.4"
midir = "0.9.1"
