[package]
name = "midi_driver"
version = "0.1.0"
edition = "2021"

[[bin]]
## Read a MIDI device and output the triples
name = "read_midi"
path = "src/midi_read.rs"

[[bin]]
## Read the tripples and translate them
name = "translate_midi"
path = "src/translate.rs"

[[bin]]
## Run programmes in response to MIDI signals on stdin
name = "command_midi"
path="src/midi_command.rs"

[[bin]]
name="main"
path="src/main.rs"

[dependencies]
alsa = "0.7.0"
jack = "0.11.4"
midir = "0.9.1"
