#!/bin/bash

set -eu
DIR=$(cd "$(dirname "$0")" && pwd)
source "${DIR}/common.sh"

SPEED=4.898
DEPTH=0.510

HOME=$(get_120Home)
JACKNAME=$(get_jackname)

wait_for_jack ${JACKNAME}

pd -path "${HOME}/basic-pure-data-audio-effects/"  -nogui -jack  -jackname ${JACKNAME} -nojackconnect -rt -send "; pd dsp 1 ; speed ${SPEED} ; depth ${DEPTH}"    -channels 1 "${HOME}/pd/chorus~.pd"
