name: Rust MIDI Driver CI

on:
  push:
    branches: [ "mistress" ]
  pull_request:
    branches: [ "mistress" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_midi_driver:
    name: Test MIDI Driver
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (ALSA)
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
    - name: Build midi_driver
      working-directory: ./midi_driver
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./midi_driver
      run: cargo test --verbose
